services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:10.11.6
    container_name: mariadb
    env_file: .env
    init: true
    restart: always
    networks:
      - network
    hostname: mariadb

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:6.5.3
    container_name: wordpress
    env_file: .env
    init: true
    restart: always
    networks:
      - network
    hostname: wordpress
    volumes:
      - wordpress_website_files:/tmp

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443/tcp"
    image: nginx:1.26.0
    container_name: nginx
    env_file: .env
    init: true
    restart: always
    networks:
      - network
    hostname: nginx
    volumes:
      - wordpress_website_files:/tmp

networks:
  network:
    driver: bridge

volumes:
  wordpress_website_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/${USER}/data/wordpress_website_files"
